export const HOME = "/";
//export const HOME2 = "/home";
//export const HOME3 = "/register1/register2/home";

export const ABOUT_PAGE = "/about";
export const LANDING_PAGE = "/landing";
export const USER_DETAILS_PAGE = "/user-details";
export const USER_DASHBOARD_PAGE = "/user-dashboard";
export const USER_PROFILE_PAGE = "/user-dashboard/profile";
export const USER_SETTINGS_PAGE = "/user-dashboard/settings";
export const EVENTS_PAGE = "/events";
export const USER_EVENTS_PAGE = "/user-dashboard/events";
export const FCEO ="/fceo";
export const BMC_REGIST = "/bmc/register"
export const FCEO_REGIST = "/fceo/register"
export const FCEO_REGIST_LEADER = "/fceo/register/leader"
export const FCEO_REGIST_MEMBER_1 = "/fceo/register/member/1"
export const FCEO_REGIST_MEMBER_2 = "/fceo/register/member/2"
export const FCEO_REGIST_SUMMARY = "/fceo/register/summary"